# Generated by Django 4.1.5 on 2023-07-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicelog",
            name="check_in",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="devicelog",
            name="check_out",
            field=models.DateTimeField(null=True),
        ),
    ]
